### ISSUE TITLE
platformio libraries

### ISSUE THREAD

**Issue by pizvizdik** [pra22/GC-20#2]
hi, i am getting error during compilation in platformio:

src/main.cpp:13:25: fatal error: WifiManager.h: No such file or directory

i tried to reinstall libraries (wifimanager) but no luck.. any ideas what is causing this error?

thank you..

**Comment by manuelchaves** [comment]
Hi, in src/main.ccp include this line:

#include <Wire.h>

**Comment by pizvizdik** [comment]
already tried that, still getting same err.. but funny thing - error only shows under linux (pop OS), in windows everything seems to be OK, upload seems finished but nothing on display:

src/main.cpp:13:25: fatal error: WifiManager.h: No such file or directory

*********************************************************************
* Looking for WifiManager.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WifiManager.h"
* Web  > https://platformio.org/lib/search?query=header:WifiManager.h
*
*********************************************************************

 #include <WifiManager.h>
                         ^
compilation terminated.
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/WiFiClientSecureAxTLS.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pio/build/nodemcuv2/lib9f2/ESP8266WiFi/WiFiServer.cpp.o
*** [.pio/build/nodemcuv2/src/main.cpp.o] Error 1

**Comment by pizvizdik** [comment]
tried to reinstall linux (pop os) with fresh installation of visual code, but still getting error:

src/main.cpp:13:25: fatal error: WifiManager.h: No such file or directory

*********************************************************************
* Looking for WifiManager.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WifiManager.h"
* Web  > https://platformio.org/lib/search?query=header:WifiManager.h
*
*********************************************************************

 #include <WifiManager.h>
                         ^
compilation terminated.
Indexing .pio/build/nodemcuv2/lib052/libAdafruit GFX Library_ID13.a
Compiling .pio/build/nodemcuv2/libb9f/Adafruit STMPE610_ID377/Adafruit_STMPE610.cpp.o
Compiling .pio/build/nodemcuv2/libc4a/Adafruit TouchScreen_ID5430/TouchScreen.cpp.o
Compiling .pio/build/nodemcuv2/lib4a5/Adafruit ILI9341_ID571/Adafruit_ILI9341.cpp.o
Compiling .pio/build/nodemcuv2/libb5b/XPT2046_Touchscreen_ID542/XPT2046_Touchscreen.cpp.o
*** [.pio/build/nodemcuv2/src/main.cpp.o] Error 1
================================================================================= [FAILED] Took 1.94 seconds =================================================================================
The terminal process terminated with exit code: 1

**Comment by Pusmos** [comment]
Hi, I am having problems with uploading the code aswell. I am very new to using PlatformIO or anything for that matter and I am hoping someone would be so kind and help me fix this Issue. I downloaded the Github Page, Installed VS Code and PlatformIO, plugged in the D1 Mini and opened the .ini file and then clicked Upload. This is what I keep getting: (Sorry for the long text) 

> Executing task: C:\Users\Raphael.Catchpole\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
----------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 2.5.3 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 160MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20701.0 (2.7.1)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - tool-mkspiffs 1.200.0 (2.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Adafruit GFX Library> 1.9.0
|   |-- <Adafruit BusIO> 1.3.3
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <Adafruit ILI9341> 1.5.5
|   |-- <Adafruit GFX Library> 1.9.0
|   |   |-- <Adafruit BusIO> 1.3.3
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Adafruit STMPE610> 1.1.2
|   |   |-- <SPI> 1.0
|   |-- <Adafruit TouchScreen> 1.1.0
|   |-- <SPI> 1.0
|-- <XPT2046_Touchscreen> 0.0.0-alpha+sha.26b691b2c8
|   |-- <SPI> 1.0
|-- <WifiManager> 0.15.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <SPI> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <EEPROM> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <Ethernet(esp8266)> 1.0.4
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio\build\nodemcuv2\libe52\Adafruit BusIO_ID6214\Adafruit_BusIO_Register.cpp.o
Compiling .pio\build\nodemcuv2\libe52\Adafruit BusIO_ID6214\Adafruit_I2CDevice.cpp.o
Compiling .pio\build\nodemcuv2\libb21\Adafruit GFX Library_ID13\Adafruit_MonoOLED.cpp.o
Compiling .pio\build\nodemcuv2\lib217\Adafruit STMPE610_ID377\Adafruit_STMPE610.cpp.o
In file included from .pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214/Adafruit_BusIO_Register.h:1:0,
                 from .pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214\Adafruit_BusIO_Register.cpp:1:
.pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214/Adafruit_I2CDevice.h:1:18: fatal error: Wire.h: No such file
or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

 #include <Wire.h>
                  ^
compilation terminated.
*** [.pio\build\nodemcuv2\libe52\Adafruit BusIO_ID6214\Adafruit_BusIO_Register.cpp.o] Error 1
In file included from .pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214\Adafruit_I2CDevice.cpp:1:0:
.pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214/Adafruit_I2CDevice.h:1:18: fatal error: Wire.h: No such file
or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

 #include <Wire.h>
                  ^
compilation terminated.
*** [.pio\build\nodemcuv2\libe52\Adafruit BusIO_ID6214\Adafruit_I2CDevice.cpp.o] Error 1
In file included from .pio\libdeps\nodemcuv2\Adafruit GFX Library_ID13\Adafruit_MonoOLED.h:30:0,
                 from .pio\libdeps\nodemcuv2\Adafruit GFX Library_ID13\Adafruit_MonoOLED.cpp:20:
.pio\libdeps\nodemcuv2\Adafruit BusIO_ID6214/Adafruit_I2CDevice.h:1:18: fatal error: Wire.h: No such file
or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

 #include <Wire.h>
                  ^
compilation terminated.
*** [.pio\build\nodemcuv2\libb21\Adafruit GFX Library_ID13\Adafruit_MonoOLED.cpp.o] Error 1
.pio\libdeps\nodemcuv2\Adafruit STMPE610_ID377\Adafruit_STMPE610.cpp:32:18: fatal error: Wire.h: No such file or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

 #include <Wire.h>
                  ^
compilation terminated.
*** [.pio\build\nodemcuv2\lib217\Adafruit STMPE610_ID377\Adafruit_STMPE610.cpp.o] Error 1
======================================= [FAILED] Took 5.33 seconds =======================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

**Comment by pizvizdik** [comment]
SOLVED!!! :3
it was problem with my windows PC, after fresh install my code is uploaded to esp, sweet :)
