### ISSUE TITLE
voltage problem

### ISSUE THREAD

**Issue by pizvizdik** [pra22/GC-20#4]
sorry for starting this new thread..

i have now problem with voltage, max output i am getting for tube is around 280V.. i checked every component before soldering it to the board and to be sure, tried to make a new board with fresh components - no progress..
could be trimmer the one to blame?

thank you, for your time..

**Comment by wlianmin** [comment]
> sorry for starting this new thread..
> 
> i have now problem with voltage, max output i am getting for tube is around 280V.. i checked every component before soldering it to the board and to be sure, tried to make a new board with fresh components - no progress..
> could be trimmer the one to blame?
> 
> thank you, for your time..

The internal resistance of a voltage meter is around 10MΩ。
So the actual voltage on the tube  should be 411.6V（tube‘s internal resistance ≈ ∞）
![2](https://user-images.githubusercontent.com/7938525/91027134-40e73600-e62e-11ea-817e-56a63f4ae318.png)

**Comment by pizvizdik** [comment]
my mistake.. thank you very much for explaining :) device is working like a charm :3

**Comment by aminhusni** [comment]
> > sorry for starting this new thread..
> > i have now problem with voltage, max output i am getting for tube is around 280V.. i checked every component before soldering it to the board and to be sure, tried to make a new board with fresh components - no progress..
> > could be trimmer the one to blame?
> > thank you, for your time..
> 
> The internal resistance of a voltage meter is around 10MΩ。 So the actual voltage on the tube should be 411.6V（tube‘s internal resistance ≈ ∞） ![2](https://user-images.githubusercontent.com/7938525/91027134-40e73600-e62e-11ea-817e-56a63f4ae318.png)

Won't that mean the voltage drop across the tube is only 280v? The tube's recommended working voltage is still 350 volts - 475 volts.
